### ISSUE TITLE
Class names

### ISSUE THREAD

**Issue by sambaptista** [Ecodev/natural-layout#1]
L'état actuel étant prototipique, je n'ai pas réfléchi en profondeur au nom des classes, mais en faite il y a un truc que j'aimais bien dans tailwind, c'est le préfixe qui conditionne le breakpoint concerné par la classe qui vient derrière  `md:horizontal`

Donc on aurait, avant : 

```
.nat-horizontal
.nat-horizontal-md
.nat-gap
.nat-gap-md
.nat-gap-md-10
```

Après  :
```
.horizontal
.md:horizontal
.gap
.md:gap
.md:gap-10
```

L'avantage évident c'est qu'en un coup d'oeil on voit les classes concernées par le breakpoint qu'on cherche. Et ce serait d'autant plus vrai si on peut garantir le tri des classes par ordre de breakout croissant (si c'est pas trop compliqué à faire) :  

```html
<div class="vertical gap md:horizontal md:gap-10 lg:gap-20>
```

On pourrait namespacer, mais avec cette syntaxe, je l'abandonnerait. Les seuls autres css qu'on utilise viennent de material et sont déjà namespacés.

**Comment by PowerKiKi** [comment]
En essayant le proto, j'ai instinctivement taper "hori" et auto-compléter pour découvrir les breakpoints (dont j'ignorais l'existence). J'ai trouvé la découverte de l'API sympa. Avec le breakpoint en début, on aura pas tout à fait la même expérience, mais PhpStorm complète aussi au milieu du mot. Donc dans le fond, ce sera pas si différent que cela.

Je crois pas avoir un avis marqué envers l'une ou l'autre alternative. Et je m'habituerai probablement vite à ce qui est choisit.

En revanche je pense qu'on doit quand même conserver le préfixe de lib "nat-". Parce qu'on si on utilise peu d'autre classes, les styles de natural-layout seront globaux et on utilise quand même d'autre lib qui elles aussi ont du style global. Je pense en particulier au lib non-Angular, tel que natural-gallery (!), quilljs, highcharts, peut-être chart.js, prosemirror. Le risque n'est pas énorme, mais il est non-null, et si cela se produit, cela va être infernal à identifier et encore plus à corriger. Je pense que garder le préfixe de lib est le choix le plus sûr.

PS: le préfixe de lib n'entrave pas le potentiel avantage des classes listée dans l'ordre alphabétique si on choisit d'avoir le breakpoint au début
